services:
  zilla:
    image: ghcr.io/aklivity/zilla:latest
    depends_on:
      - kafka
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
      #- 4444:4444
    environment:
      ZILLA_INCUBATOR_ENABLED: "true"
      SASL_USERNAME: ${SASL_USERNAME:-alice}
      SASL_PASSWORD: ${SASL_PASSWORD:-secret}
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      FTP_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      ftp_proxy: ""
      no_proxy: ""
      #JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4444
    volumes:
      - ./specs/light-openapi.yaml:/etc/zilla/light-openapi.yaml
      - ./specs/light-asyncapi.yaml:/etc/zilla/light-asyncapi.yaml
      - ./zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e -Pzilla.engine.verbose.composites=true

  kafka:
    image: bitnami/kafka:3.5
    restart: unless-stopped
    ports:
      - 29092:29092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_BROKER_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLUSTER"
      KAFKA_CFG_LISTENERS: "CONTROLLER://:9093,CLUSTER://:9094,CLIENT://:9092,EXTERNAL://:29092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,CLUSTER:PLAINTEXT,CLIENT:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLUSTER://kafka:9094,CLIENT://kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_CFG_LOG_DIRS: "/tmp/logs"
      # KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-512"
      KAFKA_CLIENT_USERS: alice
      KAFKA_CLIENT_PASSWORDS: secret

  kafka-init:
    image: bitnami/kafka:3.5
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER:-kafka:9092}
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS:--Xmx64M}
    configs:
      - source: client.properties
        target: /tmp/client.properties
    command:
      - "bash"
      - "-c"
      - "echo Creating topics for $${KAFKA_BOOTSTRAP_SERVER};
        /opt/bitnami/kafka/bin/kafka-topics.sh --command-config /tmp/client.properties --bootstrap-server $${KAFKA_BOOTSTRAP_SERVER} --create --if-not-exists --topic requests;
        /opt/bitnami/kafka/bin/kafka-topics.sh --command-config /tmp/client.properties --bootstrap-server $${KAFKA_BOOTSTRAP_SERVER} --create --if-not-exists --topic responses;"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8182:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      #KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAIN
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${USERNAME}" password="${PASSWORD}";'
  #     DYNAMIC_CONFIG_ENABLED: true

networks:
  default:
    driver: bridge

configs:
  client.properties:
    content: |
      sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${SASL_USERNAME:-alice}" password="${SASL_PASSWORD:-secret}";
      security.protocol=${SASL_PROTOCOL:-SASL_PLAINTEXT}
      sasl.mechanism=SCRAM-SHA-512
